### ISSUE TITLE
Eigen version?

### ISSUE THREAD

**Issue by antithing** [toniortiz/rgbd-slam#1]
Hi, and thank you for making this code available. I am trying to build it in windows, visual studio, and am seeing some errors.
The CMakelists says Eigen 3.0, but OpenGv needs Eigen 2, it won't build with Eigen 3, or do you use a custom branch?

Thanks!

**Comment by toniortiz** [comment]
Hello,

opengv needs Eigen 3, https://laurentkneip.github.io/opengv/page_installation.html

________________________________
De: antithing <notifications@github.com>
Enviado: lunes, 22 de julio de 2019 05:02 a. m.
Para: toniortiz/rgbd-slam <rgbd-slam@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [toniortiz/rgbd-slam] Eigen version? (#1)


Hi, and thank you for making this code available. I am trying to build it in windows, visual studio, and am seeing some errors.
The CMakelists says Eigen 3.0, but OpenGv needs Eigen 2, it won't build with Eigen 3, or do you use a custom branch?

Thanks!

**Comment by antithing** [comment]
Hi! I seem to have hit a windows issue where opengv only builds in debug mode.

However, after looking through your code, it seems that opengv is not actually used? 
I stripped out the includes and it builds fine. Is this right? 

I have it running using the Gicp solver. I uncommented the local ba, but the result is not great until after the final, global ba. 
Is this what you see? 


Thanks again!

**Comment by toniortiz** [comment]
You're right opengv is optional. I included it only for testing different algorithms.

With local ba the results are unsatisfactory; this is commented. However when a loop closure is detected, I perform global ba and the results are good.
________________________________
De: antithing <notifications@github.com>
Enviado: jueves, 25 de julio de 2019 01:04 a. m.
Para: toniortiz/rgbd-slam <rgbd-slam@noreply.github.com>
CC: Antonio Ortiz <toniortizg@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [toniortiz/rgbd-slam] Eigen version? (#1)


Hi! I seem to have hit a windows issue where opengv only builds in debug mode.

However, after looking through your code, it seems that opengv is not actually used?
I stripped out the includes and it builds fine. Is this right?

I have it running using the Gicp solver. I uncommented the local ba, but the result is not great until after the final, global ba.
Is this what you see?

Thanks again!
